### PR TITLE
refactor: `campaign-editor` → `admin-campaigns`

### LINKED ISSUE #223: refactor: rename `@givewp/app` to `@givewp/admin`
This renames `@givewp/app` to `@givewp/admin` following the reasoning outlined in #210. This also renamed the `campaign-editor` directory to `campaigns` after the name of the Donations submenu item. Sibling directories in this directory will named after other Donations sidebar items. Further refactoring/organization will need to take place within this workspace.

## Acceptance Criteria

- [x] Renames `@givewp/app` to `@givewp/admin`
- [x] Reflects the directory names in the epic
- [x] All references to the path names are update
- [x] JS bundle file name is changed from `admin.js` to `campaigns.js`

### PR DESCRIPTION
**Pull request by knowler**
## Description

Resolves #223 — see that issue for more details.

## How Has This Been Tested?

Still builds 👍 

## Types of changes

Refactoring/renaming.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by knowler** [comment]
> I'm trying to keep a uniformity of organization going as much as possible between projects.

I definitely appreciate the push for consistency between projects.

Ok, I’m game with that then, however, I think that the location of the client (or app — i.e. `ReactDOM.render()`) should also the be a Yarn workspace, since I don’t think that clients should share dependencies, so I am suggesting the following changes:

```bash
.
└── resources
   └── js
      └── app
         ├── admin-campaigns
         │  └── package.json
         ├── admin-reports
         │  └── package.json
         ├── campaigns-embed
         │  └── package.json
         └── campaigns-landing
            └── package.json
```

**Comment by JasonTheAdams** [comment]
Having a `package.json` for each application seems unnecessary. None of these applications will be pulled outside of the context of the project (at large), so what's the benefit of having distinct dependencies between each application?

**Comment by knowler** [comment]
Sounds good — I will not go ahead with making workspaces for each app. Does the sub-directory naming scheme make sense?

**Comment by JasonTheAdams** [comment]
Yup, I'm cool with the sub-directories!

**Comment by knowler** [comment]
Ok, this is ready now. 👍

**Pull request merged**
