### PR TITLE
chore: move contents of campaign-editor to app

### PR DESCRIPTION
**Pull request by knowler**
## Description

This is a no impact, code organizational change.

## How Has This Been Tested?

It still works

## Types of changes

Code organization

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@knowler What's the thinking behind this?

**Comment by knowler** [comment]
Some of the paths are getting out of hand. Example:

```
resources/js/app/campaign-editor/campaign-types/general-fundraising/settings/CampaignIntroduction/sections/introductions.jsx
```

**Comment by JasonTheAdams** [comment]
Please hold off on merging this until we have a chance to discuss post-prototype details.

**Comment by knowler** [comment]
I’m going to close this for the time being. I’ll make an issue with some file/folder structural proposals.

**Pull request closed without merging**
